const SUPABASE_URL='https://rugakupxctxbfhbgbksy.supabase.co';
const SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1Z2FrdXB4Y3R4YmZoYmdia3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc2MzMwMDcsImV4cCI6MjEwMzIwOTAwN30.mVWan9bB3zu0J-US6XJ-pVJfAffG1wP-D1Ze_G7-YpU';
const {createClient}=supabase; const db=createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s); const app=$('#app');
let products=[],cart=JSON.parse(localStorage.getItem('sparkle-cart')||'[]'),user=null,isAdmin=false,currentConv=null;
const fallbackImg='logo.jpg';
function money(n){return '₹'+Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:0})}
function toast(t){let e=document.createElement('div');e.className='toast glass';e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.classList.add('show'),20);setTimeout(()=>{e.classList.remove('show');setTimeout(()=>e.remove(),300)},2600)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function loadProducts(){const {data,error}=await db.from('products').select('*').order('created_at',{ascending:false});if(error){console.error(error);products=[]}else products=data||[];render()}
function render(){
  app.innerHTML=`<div class="shell"><nav class="nav"><a class="brand" href="#top" style="color:inherit;text-decoration:none"><img src="logo.jpg"><div><strong>Sparkle Stitches</strong><small>Embroidery & Design</small></div></a><div class="nav-actions">${user?'<button class="btn ghost" onclick="openMyOrders()">Orders</button>':''}<button class="btn ghost" onclick="openAuth()">${user?'Account':'Login'}</button><button class="btn gold" onclick="openCart()">Bag <span id="cartCount">${cart.reduce((a,x)=>a+x.qty,0)}</span></button></div></nav><main id="top"><section class="hero"><div><div class="eyebrow">Handcrafted • Elegant • Made with love</div><h1>Wear your <span>sparkle.</span></h1><p>Premium blouse ari work and embroidery designs crafted to make every celebration feel extraordinary.</p><div class="tools"><button class="btn gold" onclick="document.querySelector('#collection').scrollIntoView({behavior:'smooth'})">Explore designs</button><button class="btn" onclick="openChat()">Chat with us</button><button class="btn" onclick="openCustomOrder()">Custom order</button></div><div class="stats"><div class="stat glass"><b>Handcrafted</b><span class="muted">Fine ari work</span></div><div class="stat glass"><b>Custom orders</b><span class="muted">Made for you</span></div><div class="stat glass"><b>Support</b><span class="muted">Direct chat</span></div></div></div><div class="hero-card glass"><img src="logo.jpg" alt="Sparkle Stitches"></div></section><section class="section" id="collection"><div class="section-head"><div><div class="eyebrow">The collection</div><h2>Signature designs</h2></div><input id="search" class="input search" placeholder="Search designs…" oninput="filterProducts()"></div><div id="products" class="grid"></div></section></main><footer class="footer">© ${new Date().getFullYear()} Sparkle Stitches · Embroidery & Design</footer></div><div id="modal" class="modal"></div><style>
.order-card{padding:16px;border-radius:18px;margin-bottom:14px}.order-badge{padding:6px 10px;border-radius:999px;font-size:12px;font-weight:700}.order-badge.active{background:rgba(212,175,55,.14);color:var(--gold)}.order-badge.shipped{background:rgba(80,150,255,.14);color:#7eb5ff}.order-badge.delivered{background:rgba(70,200,120,.14);color:#72d89a}.order-badge.cancelled{background:rgba(255,80,80,.14);color:#ff8585}.order-items{margin:14px 0;border-top:1px solid rgba(255,255,255,.08);border-bottom:1px solid rgba(255,255,255,.08);padding:10px 0}.order-item,.order-summary{display:flex;justify-content:space-between;gap:12px;padding:6px 0}.order-progress{display:grid;grid-template-columns:repeat(6,1fr);gap:4px;margin:16px 0}.order-step{text-align:center;opacity:.42}.order-step.done{opacity:1}.order-step span{display:block;font-size:16px}.order-step small{display:block;font-size:9px;line-height:1.15}.order-cancelled{padding:12px;border-radius:12px;background:rgba(255,80,80,.1);color:#ff8585;font-weight:700;margin:14px 0}.my-orders{max-height:70vh;overflow:auto;padding-right:2px}.product-detail{display:grid;gap:15px}.product-detail-img{width:100%;max-height:360px;object-fit:cover;border-radius:18px}.product-gallery{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.product-gallery img{width:100%;height:72px;object-fit:cover;border-radius:10px;cursor:pointer;opacity:.75}.product-gallery img.active{opacity:1;outline:1px solid var(--gold)}.size-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px}.size-option{display:flex;align-items:center;justify-content:space-between;padding:11px;border:1px solid rgba(255,255,255,.1);border-radius:14px}.size-option.selected{border-color:var(--gold);background:rgba(212,175,55,.08)}.size-admin-grid,.photo-admin-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.size-admin-grid label{font-size:12px}.size-price{color:var(--gold);font-weight:700}.notify-list{max-height:55vh;overflow:auto}.notify-item{padding:12px;border-bottom:1px solid rgba(255,255,255,.08)}.notify-item.unread{background:rgba(212,175,55,.07)}.liquid-touch{position:absolute;width:18px;height:18px;border-radius:50%;pointer-events:none;background:radial-gradient(circle,rgba(255,255,255,.42),rgba(212,175,55,.22) 38%,transparent 72%);transform:translate(-50%,-50%) scale(.7);animation:liquidTouch .72s cubic-bezier(.18,.8,.18,1) forwards;z-index:99}@keyframes liquidTouch{to{transform:translate(-50%,-50%) scale(8);opacity:0}}.btn{position:relative;overflow:hidden;-webkit-tap-highlight-color:transparent}
</style>`;drawProducts();if(!window.__sparkleTouch){window.__sparkleTouch=true;document.addEventListener('pointerdown',e=>{const b=e.target.closest?.('.btn');if(!b)return;const r=b.getBoundingClientRect(),s=document.createElement('span');s.className='liquid-touch';s.style.left=(e.clientX-r.left)+'px';s.style.top=(e.clientY-r.top)+'px';b.appendChild(s);setTimeout(()=>s.remove(),750)},{passive:true})}
}
function drawProducts(){let q=($('#search')?.value||'').toLowerCase();let list=products.filter(p=>p.is_active!==false&&(p.name+' '+p.category+' '+p.description).toLowerCase().includes(q));let el=$('#products');if(!el)return;el.innerHTML=list.length?list.map(p=>{const prices=productSizePrices(p),vals=Object.values(prices).map(Number).filter(Boolean),min=vals.length?Math.min(...vals):Number(p.price||0),max=vals.length?Math.max(...vals):min;return `<article class="card glass" onclick="openProduct('${p.id}')"><img class="card-img" src="${esc(p.image_url||fallbackImg)}" onerror="this.src='logo.jpg'"><div class="card-body"><div class="tag">${esc(p.category||'Design')}</div><h3>${esc(p.name)}</h3><p class="muted">${esc(p.description||'')}</p><div class="row"><div class="price">${vals.length&&min!==max?money(min)+' – '+money(max):money(min)}</div><button class="btn gold" onclick="event.stopPropagation();openProduct('${p.id}')">View details</button></div></div></article>`}).join(''):`<div class="empty" style="grid-column:1/-1">No designs yet. Add your first design from the admin panel.</div>`}
function productSizePrices(p){let x=p?.size_prices;if(!x)return {};if(typeof x==='object')return x;try{return JSON.parse(x)}catch(e){return {}}}
function productSizes(p){const x=Object.keys(productSizePrices(p));return x.length?x:['XS','S','M','L','XL','XXL']}
function productPriceForSize(p,size){const x=productSizePrices(p);return Number(x[size]??p.price??0)}
function productImages(p){return [p?.image_url,p?.image_url_2,p?.image_url_3,p?.image_url_4].filter(Boolean)}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;window.__selectedProductId=id;const imgs=productImages(p),sizes=productSizes(p),first=imgs[0]||fallbackImg;modal(`<div class="modal-head"><div><div class="eyebrow">${esc(p.category||'Design')}</div><h3>${esc(p.name)}</h3></div><button class="btn" onclick="closeModal()">×</button></div><div class="product-detail"><img id="productMainImage" class="product-detail-img" src="${esc(first)}" onerror="this.src='logo.jpg'><div class="product-gallery">${imgs.map((u,i)=>`<img class="${i===0?'active':''}" src="${esc(u)}" onclick="chooseProductImage(this,'${esc(u)}')">`).join('')}</div><p>${esc(p.description||'No description provided.')}</p><div class="notice"><b>Making time:</b> ${esc(p.production_time||'Admin has not set a time yet')}</div><div><div class="eyebrow">Choose size</div><div class="size-grid">${sizes.map((s,i)=>`<label class="size-option ${i===0?'selected':''}" onclick="selectProductSize(this)"><span><input type="radio" name="productSize" value="${esc(s)}" ${i===0?'checked':''}> ${esc(s)}</span><span class="size-price">${money(productPriceForSize(p,s))}</span></label>`).join('')}</div></div><div class="row"><strong id="selectedProductPrice">${money(productPriceForSize(p,sizes[0]))}</strong><button class="btn gold" onclick="addSelectedToCart('${p.id}')">Add to bag</button></div></div>`)}
function chooseProductImage(el,url){const main=$('#productMainImage');if(main)main.src=url;document.querySelectorAll('.product-gallery img').forEach(x=>x.classList.remove('active'));el.classList.add('active')}
function selectProductSize(el){document.querySelectorAll('.size-option').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');const p=products.find(x=>x.id===window.__selectedProductId),s=el.querySelector('input')?.value;if(p&&s&&$('#selectedProductPrice'))$('#selectedProductPrice').textContent=money(productPriceForSize(p,s))}
function filterProducts(){drawProducts()}
function modal(content){$('#modal').innerHTML=`<div class="modal-box glass">${content}</div>`;$('#modal').classList.add('open');$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()}}
function closeModal(){$('#modal')?.classList.remove('open')}
function addToCart(id,size){const p=products.find(x=>x.id===id);if(!p)return;size=size||productSizes(p)[0]||'M';let x=cart.find(x=>x.id===id&&(x.size||'M')===size);if(x)x.qty++;else cart.push({id,size,qty:1});saveCart();toast('Added to your bag ✨')}
function addSelectedToCart(id){addToCart(id,document.querySelector('input[name="productSize"]:checked')?.value);closeModal()}
function saveCart(){localStorage.setItem('sparkle-cart',JSON.stringify(cart));let c=$('#cartCount');if(c)c.textContent=cart.reduce((a,x)=>a+x.qty,0)}
function openCart(){let rows=cart.map(x=>{let p=products.find(p=>p.id===x.id);return p?`<div class="cart-item"><img src="${esc(p.image_url||fallbackImg)}"><div><b>${esc(p.name)}</b><div class="muted">Size: ${esc(x.size||'M')} · ${money(productPriceForSize(p,x.size||'M'))}</div></div><div class="qty"><button onclick="changeQty('${p.id}','${esc(x.size||'M')}',-1)">−</button><b>${x.qty}</b><button onclick="changeQty('${p.id}','${esc(x.size||'M')}',1)">+</button></div></div>`:''}).join('');let total=cart.reduce((a,x)=>{let p=products.find(p=>p.id===x.id);return a+(p?productPriceForSize(p,x.size||'M')*x.qty:0)},0);modal(`<div class="modal-head"><div><div class="eyebrow">Your selection</div><h3>Shopping bag</h3></div><button class="btn" onclick="closeModal()">×</button></div>${rows||'<div class="empty">Your bag is waiting for something beautiful.</div>'}${rows?`<div class="row" style="padding-top:18px"><b>Total</b><strong style="font-size:25px;color:var(--gold)">${money(total)}</strong></div><button class="btn gold" style="width:100%;margin-top:15px" onclick="checkout()">Continue to checkout</button>`:''}`)}
function changeQty(id,size,d){let x=cart.find(x=>x.id===id&&(x.size||'M')===size);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(x=>!(x.id===id&&(x.size||'M')===size));saveCart();openCart()}

function orderStatusLabel(status){
  const map={RECEIVED:'Order received',PROCESSING:'Processing',EMBROIDERY:'Embroidery',READY:'Ready for dispatch',SHIPPED:'Shipped',DELIVERED:'Delivered',CANCELLED:'Cancelled'};
  return map[status]||status||'Order received';
}
function orderStatusClass(status){
  return status==='CANCELLED'?'cancelled':status==='DELIVERED'?'delivered':status==='SHIPPED'?'shipped':'active';
}
function orderSteps(status){
  const steps=['RECEIVED','PROCESSING','EMBROIDERY','READY','SHIPPED','DELIVERED'];
  if(status==='CANCELLED')return `<div class="order-cancelled">✕ Order cancelled</div>`;
  const current=Math.max(0,steps.indexOf(status));
  return `<div class="order-progress">${steps.map((s,i)=>`<div class="order-step ${i<=current?'done':''}"><span>${i<current?'✓':i===current?'●':'○'}</span><small>${orderStatusLabel(s)}</small></div>`).join('')}</div>`;
}
async function openMyOrders(){
  if(!user){openAuth();return}
  const {data:orders,error}=await db.from('orders').select('*').eq('user_id',user.id).order('created_at',{ascending:false});
  if(error)return toast(error.message);
  const ids=(orders||[]).map(o=>o.id);
  let items=[];
  if(ids.length){
    const r=await db.from('order_items').select('*').in('order_id',ids);
    if(r.error)return toast(r.error.message);
    items=r.data||[];
  }
  const cards=(orders||[]).map(o=>{
    const its=items.filter(i=>i.order_id===o.id);
    return `<article class="order-card glass">
      <div class="row"><div><div class="eyebrow">Order</div><b>#${esc(o.id.slice(0,8).toUpperCase())}</b></div><span class="order-badge ${orderStatusClass(o.order_status)}">${esc(orderStatusLabel(o.order_status))}</span></div>
      <div class="muted" style="margin-top:6px">${new Date(o.created_at).toLocaleString('en-IN')}</div>
      <div class="order-items">${its.map(i=>`<div class="order-item"><span>${esc(i.product_name)} × ${i.quantity}</span><b>${money(Number(i.unit_price)*Number(i.quantity))}</b></div>`).join('')||'<div class="muted">Order details unavailable.</div>'}</div>
      ${orderSteps(o.order_status)}
      <div class="order-summary"><span>Payment: <b>${esc(o.payment_status||'PENDING')}</b></span><strong>${money(o.total_amount)}</strong></div>
      ${o.order_status==='CANCELLED'?'<div class="notice">This order was cancelled. Please contact support if you need help.</div>':''}
    </article>`;
  }).join('');
  modal(`<div class="modal-head"><div><div class="eyebrow">Your account</div><h3>My Orders</h3></div><button class="btn" onclick="closeModal()">×</button></div>
  <div class="my-orders">${cards||'<div class="empty">You have not placed any orders yet.</div>'}</div>`);
}

async function openAuth(){if(user){await refreshAdmin();modal(`<div class="modal-head"><div><div class="eyebrow">Welcome back</div><h3>${esc(user.email)}</h3></div><button class="btn" onclick="closeModal()">×</button></div><div class="form"><button class="btn gold" style="width:100%" onclick="openMyOrders()">📦 My Orders</button><button class="btn" style="width:100%" onclick="openNotifications()">🔔 Notifications</button>${isAdmin?'<button class="btn gold" style="width:100%" onclick="openAdmin()">👑 Admin Dashboard</button>':''}<button class="btn" style="width:100%" onclick="signOut()">Sign out</button></div>`);return}modal(`<div class="modal-head"><div><div class="eyebrow">Secure access</div><h3>Sign in</h3></div><button class="btn" onclick="closeModal()">×</button></div><p class="muted">Enter your email to receive a 6-digit code.</p><div class="form"><input id="email" class="input" type="email" placeholder="Enter email"><button class="btn gold" onclick="sendEmailOtp()">Send email OTP</button></div>`)}
async function sendEmailOtp(){let email=$('#email').value.trim();if(!email)return toast('Enter your email');let {error}=await db.auth.signInWithOtp({email,options:{shouldCreateUser:true}});if(error)return toast(error.message);modal(`<div class="eyebrow">Check your inbox</div><h3>Enter your OTP</h3><p class="muted">We sent a 6-digit code to ${esc(email)}.</p><div class="form"><input id="otpEmail" class="input otp" maxlength="6" inputmode="numeric" placeholder="••••••"><button class="btn gold" onclick="verifyEmailOtp('${esc(email)}')">Verify & continue</button></div>`)}
async function verifyEmailOtp(email){let token=($('#otpEmail')?.value||'').trim();if(!/^\d{6}$/.test(token))return toast('Enter the 6-digit code');let {data,error}=await db.auth.verifyOtp({email,token,type:'email'});if(error)return toast(error.message);user=data.user;await refreshAdmin();try{await db.from('login_activity').insert({user_id:user.id,email:user.email,is_admin:isAdmin})}catch(e){console.warn('login activity',e)}closeModal();toast(isAdmin?'Welcome, Admin ✨':'Welcome to Sparkle Stitches ✨');render()}
async function signOut(){await db.auth.signOut();user=null;isAdmin=false;closeModal();render()}
async function refreshAdmin(){isAdmin=false;if(!user)return;try{const {data,error}=await db.rpc('is_admin');if(error)console.warn('Admin check:',error);isAdmin=!!data}catch(e){isAdmin=false}}
async function checkout(){if(!user){closeModal();openAuth();return}if(!cart.length)return;let total=cart.reduce((a,x)=>{let p=products.find(p=>p.id===x.id);return a+(p?productPriceForSize(p,x.size||'M')*x.qty:0)},0),saved=JSON.parse(localStorage.getItem('sparkle-checkout-identities')||'[]');modal(`<div class="modal-head"><div><div class="eyebrow">Almost yours</div><h3>Checkout</h3></div><button class="btn" onclick="closeModal()">×</button></div><form class="form" onsubmit="placeOrder(event,${total})"><label class="muted">Previously used details</label><select class="select" onchange="applySavedIdentity(this.value)"><option value="">Use new details</option>${saved.map((s,i)=>`<option value="${i}">${esc(s.name)} · ${esc(s.city)} · ${esc(s.pincode)}</option>`).join('')}</select><div class="two"><input class="input" id="checkoutName" name="name" placeholder="Full name" required><input class="input" id="checkoutPhone" name="phone" placeholder="Mobile number" required></div><textarea class="textarea" id="checkoutAddress" name="address" placeholder="Full delivery address" rows="3" required></textarea><div class="two"><input class="input" id="checkoutCity" name="city" placeholder="City" required><input class="input" id="checkoutPincode" name="pincode" placeholder="PIN code" required></div><select class="select" name="payment"><option value="COD">Cash on Delivery</option><option value="UPI_MANUAL">UPI — payment confirmation</option></select><div class="notice">Total: <b>${money(total)}</b></div><button class="btn gold" type="submit">Place order</button></form>`)}
function applySavedIdentity(i){if(i==='')return;let a=JSON.parse(localStorage.getItem('sparkle-checkout-identities')||'[]')[Number(i)];if(!a)return;$('#checkoutName').value=a.name||'';$('#checkoutPhone').value=a.phone||'';$('#checkoutAddress').value=a.address||'';$('#checkoutCity').value=a.city||'';$('#checkoutPincode').value=a.pincode||''}
async function placeOrder(e,total){e.preventDefault();let f=new FormData(e.target),identity={name:f.get('name'),phone:f.get('phone'),address:f.get('address'),city:f.get('city'),pincode:f.get('pincode')},saved=JSON.parse(localStorage.getItem('sparkle-checkout-identities')||'[]');saved=[identity,...saved.filter(x=>JSON.stringify(x)!==JSON.stringify(identity))].slice(0,5);localStorage.setItem('sparkle-checkout-identities',JSON.stringify(saved));let {data:order,error}=await db.from('orders').insert({user_id:user.id,customer_name:identity.name,customer_email:user.email,customer_phone:identity.phone,address:identity.address,city:identity.city,pincode:identity.pincode,total_amount:total,payment_method:f.get('payment')}).select().single();if(error)return toast(error.message);let items=cart.map(x=>{let p=products.find(p=>p.id===x.id);return {order_id:order.id,product_id:p.id,product_name:p.name,unit_price:productPriceForSize(p,x.size||'M'),quantity:x.qty,size:x.size||'M'}});let r=await db.from('order_items').insert(items);if(r.error)return toast(r.error.message);cart=[];saveCart();closeModal();toast('Order placed successfully ✨')}

async function uploadImage(bucket,file,pathPrefix){if(!file||!file.size)return null;if(file.size>8*1024*1024)throw new Error('Each image must be under 8 MB');if(!file.type.startsWith('image/'))throw new Error('Only image files are allowed');const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const path=`${pathPrefix}/${crypto.randomUUID()}.${ext}`;const up=await db.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type});if(up.error)throw up.error;return db.storage.from(bucket).getPublicUrl(path).data.publicUrl}
async function openCustomOrder(){if(!user){openAuth();return}modal(`<div class="modal-head"><div><div class="eyebrow">Made for you</div><h3>Custom order</h3></div><button class="btn" onclick="closeModal()">×</button></div><form id="customOrderForm" class="form"><textarea class="textarea" name="message" rows="6" maxlength="1500" placeholder="Describe your design, colours, measurements and details…" required></textarea><label class="muted">Upload up to 3 reference photos</label><input id="customPhotos" class="input" type="file" accept="image/*" multiple><button class="btn gold" type="submit">Send custom request</button></form>`);$('#customOrderForm').onsubmit=async e=>{e.preventDefault();const files=[...($('#customPhotos')?.files||[])];if(files.length>3)return toast('Maximum 3 photos allowed');try{const urls=[];for(const f of files)urls.push(await uploadImage('custom-order-images',f,user.id));const r=await db.from('custom_orders').insert({user_id:user.id,message:String(new FormData(e.target).get('message')||'').trim(),photo_urls:urls});if(r.error)throw r.error;closeModal();toast('Custom request sent ✨')}catch(err){toast(err.message||'Custom order failed')}}}
let unreadNotificationCount=0,notificationTimer=null,customerChatTimer=null,adminChatTimer=null;
async function refreshNotifications(){if(!user){unreadNotificationCount=0;return}let {data,error}=await db.from('notifications').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(30);if(!error)unreadNotificationCount=(data||[]).filter(n=>!n.read_at).length}
async function openNotifications(){if(!user){openAuth();return}let {data,error}=await db.from('notifications').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(50);if(error)return toast(error.message);modal(`<div class="modal-head"><div><div class="eyebrow">Updates</div><h3>Notifications</h3></div><button class="btn" onclick="closeModal()">×</button></div><div class="notify-list">${(data||[]).map(n=>`<div class="notify-item ${n.read_at?'':'unread'}"><b>${esc(n.title)}</b><div>${esc(n.message)}</div><small class="muted">${new Date(n.created_at).toLocaleString('en-IN')}</small></div>`).join('')||'<div class="empty">No notifications yet.</div>'}</div>`);await db.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',user.id).is('read_at',null);unreadNotificationCount=0}
async function adminNotifications(){if(!isAdmin)return;let {data,error}=await db.from('notifications').select('*').eq('admin_only',true).order('created_at',{ascending:false}).limit(50);if(error)return toast(error.message);$('#adminContent').innerHTML=`<div class="row"><div><div class="eyebrow">Alerts</div><h3>Admin notifications</h3></div><button class="btn" onclick="adminHome()">Back</button></div><div class="notify-list glass">${(data||[]).map(n=>`<div class="notify-item ${n.read_at?'':'unread'}"><b>${esc(n.title)}</b><div>${esc(n.message)}</div><small class="muted">${new Date(n.created_at).toLocaleString('en-IN')}</small></div>`).join('')||'<div class="empty">No admin notifications.</div>'}</div>`;await db.from('notifications').update({read_at:new Date().toISOString()}).eq('admin_only',true).is('read_at',null)}
async function openChat(){if(!user){openAuth();return}let {data,error}=await db.from('conversations').select('*').eq('user_id',user.id).order('updated_at',{ascending:false}).limit(1);if(error)return toast(error.message);if(data?.length)currentConv=data[0];else{let r=await db.from('conversations').insert({user_id:user.id}).select().single();if(r.error)return toast(r.error.message);currentConv=r.data}showCustomerChat()}
async function refreshCustomerChatMessages(){if(!currentConv?.id||!$('#customerMessages'))return;let {data:msgs}=await db.from('messages').select('*').eq('conversation_id',currentConv.id).order('created_at');$('#customerMessages').innerHTML=(msgs||[]).map(m=>`<div class="bubble ${m.sender_id===user.id?'me':'them'}">${esc(m.message)}</div>`).join('')||'<div class="empty">Ask us anything about designs, orders or custom work.</div>'}
async function showCustomerChat(){let {data:msgs}=await db.from('messages').select('*').eq('conversation_id',currentConv.id).order('created_at');modal(`<div class="modal-head"><div><div class="eyebrow">Sparkle Stitches</div><h3>Support chat</h3></div><button class="btn" onclick="closeModal()">×</button></div><div id="customerMessages" class="messages glass" style="border-radius:18px">${(msgs||[]).map(m=>`<div class="bubble ${m.sender_id===user.id?'me':'them'}">${esc(m.message)}</div>`).join('')||'<div class="empty">Ask us anything about designs, orders or custom work.</div>'}</div><div class="chat-send"><input id="customerMsg" class="input" placeholder="Type your message…" onkeydown="if(event.key==='Enter')sendCustomerMessage()"><button class="btn gold" onclick="sendCustomerMessage()">Send</button></div>`);if(customerChatTimer)clearInterval(customerChatTimer);customerChatTimer=setInterval(refreshCustomerChatMessages,2500)}

async function sendCustomerMessage(){let text=$('#customerMsg').value.trim();if(!text)return;let r=await db.from('messages').insert({conversation_id:currentConv.id,sender_id:user.id,message:text});if(r.error)return toast(r.error.message);$('#customerMsg').value='';refreshCustomerChatMessages()}

async function adminChats(){let {data,error}=await db.from('conversations').select('*').order('updated_at',{ascending:false});if(error)return toast(error.message);$('#adminContent').innerHTML=`<div class="chat glass"><div class="chat-list">${(data||[]).map((c,i)=>`<button class="${i===0?'active':''}" onclick="adminOpenChat('${c.id}',this)">Customer ${c.user_id.slice(0,8)}<br><small class="muted">${new Date(c.updated_at).toLocaleString()}</small></button>`).join('')||'<div class="empty">No chats yet.</div>'}</div><div id="adminChatWindow" class="chat-window"><div class="empty">Select a conversation.</div></div></div>`;if(data?.[0])adminOpenChat(data[0].id);if(adminChatTimer)clearInterval(adminChatTimer);adminChatTimer=setInterval(()=>currentConv?.id&&$('#adminChatWindow')&&refreshAdminChatMessages(),2500)}

async function refreshAdminChatMessages(){if(!currentConv?.id||!$('#adminChatWindow'))return;let {data:msgs}=await db.from('messages').select('*').eq('conversation_id',currentConv.id).order('created_at');$('#adminChatWindow').querySelector('.messages').innerHTML=(msgs||[]).map(m=>`<div class="bubble ${m.sender_id===user.id?'me':'them'}">${esc(m.message)}</div>`).join('')}

async function adminOpenChat(id,btn){currentConv={id};document.querySelectorAll('.chat-list button').forEach(x=>x.classList.remove('active'));btn?.classList.add('active');let {data:msgs}=await db.from('messages').select('*').eq('conversation_id',id).order('created_at');$('#adminChatWindow').innerHTML=`<div class="messages">${(msgs||[]).map(m=>`<div class="bubble ${m.sender_id===user.id?'me':'them'}">${esc(m.message)}</div>`).join('')||'<div class="empty">No messages yet.</div>'}</div><div class="chat-send"><input id="adminMsg" class="input" placeholder="Reply to customer…" onkeydown="if(event.key==='Enter')sendAdminMessage()"><button class="btn gold" onclick="sendAdminMessage()">Send</button><button class="btn" onclick="deleteAdminChat('${id}')">Delete chat</button></div>`}

async function sendAdminMessage(){let text=$('#adminMsg').value.trim();if(!text)return;let r=await db.from('messages').insert({conversation_id:currentConv.id,sender_id:user.id,message:text});if(r.error)return toast(r.error.message);refreshAdminChatMessages()}

async function deleteAdminChat(id){if(!confirm('Delete this chat?'))return;await db.from('messages').delete().eq('conversation_id',id);let r=await db.from('conversations').delete().eq('id',id);if(r.error)return toast(r.error.message);currentConv=null;adminChats()}

async function openAdmin(){if(!user){openAuth();return}await refreshAdmin();if(!isAdmin){toast('Admin access is restricted');return}adminHome()}
async function adminHome(){await refreshAdmin();if(!isAdmin)return toast('Admin access is restricted');modal(`<div class="modal-head"><div><div class="eyebrow">Private workspace</div><h3>Sparkle Stitches Admin</h3></div><button class="btn" onclick="closeModal()">×</button></div><div class="admin-nav"><button class="btn gold" onclick="adminProducts()">Products</button><button class="btn" onclick="adminOrders()">Orders</button><button class="btn" onclick="adminChats()">Chat</button><button class="btn" onclick="adminCustomOrders()">Custom orders</button><button class="btn" onclick="adminLoginActivity()">Login activity</button><button class="btn" onclick="adminAccounts()">Admin accounts</button><button class="btn" onclick="adminNotifications()">Notifications</button></div><div id="adminContent"></div>`);adminProducts()}
async function adminProducts(){let {data,error}=await db.from('products').select('*').order('created_at',{ascending:false});if(error)return toast(error.message);let rows=(data||[]).map(p=>`<tr><td><img src="${esc(p.image_url||fallbackImg)}" style="width:52px;height:52px;object-fit:cover;border-radius:10px"></td><td>${esc(p.name)}</td><td>${money(p.price)}</td><td>${p.is_active?'Live':'Hidden'}</td><td><button class="btn" onclick="editProduct('${p.id}')">Edit</button><button class="btn" onclick="deleteProduct('${p.id}')">Delete</button></td></tr>`).join('');$('#adminContent').innerHTML=`<div class="row" style="margin-bottom:15px"><div class="muted">Manage 4 photos, sizes, prices, description and making time.</div><button class="btn gold" onclick="editProduct()">+ Add design</button></div><div class="table-wrap glass"><table class="table"><tr><th>Image</th><th>Name</th><th>Price</th><th>Status</th><th>Actions</th></tr>${rows||'<tr><td colspan="5" class="empty">No products.</td></tr>'}</table></div>`}
async function editProduct(id){let p=id?products.find(x=>x.id===id):null,sp=productSizePrices(p);modal(`<div class="modal-head"><div><div class="eyebrow">Catalog</div><h3>${p?'Edit design':'New design'}</h3></div><button class="btn" onclick="adminHome()">×</button></div><form id="productForm" class="form"><input class="input" name="name" placeholder="Product name" value="${esc(p?.name||'')}" required><div class="two"><input class="input" name="price" type="number" min="0" step="1" placeholder="Base price" value="${p?.price||''}" required><input class="input" name="category" placeholder="Category" value="${esc(p?.category||'Blouse Ari Work')}" required></div><textarea class="textarea" name="description" rows="4" placeholder="Description">${esc(p?.description||'')}</textarea><input class="input" name="production_time" placeholder="Making time e.g. 3–5 days" value="${esc(p?.production_time||'')}"><label class="muted">Separate price for each size</label><div class="size-admin-grid">${['XS','S','M','L','XL','XXL'].map(s=>`<label>${s}<input class="input" type="number" min="0" name="size_${s}" value="${sp[s]??''}" placeholder="₹"></label>`).join('')}</div><label class="muted">Product photos — up to 4</label><div class="photo-admin-grid">${[1,2,3,4].map(i=>`<input class="input" name="image_file_${i}" type="file" accept="image/*">`).join('')}</div><div class="photo-admin-grid">${[1,2,3,4].map(i=>`<input class="input" name="image_url_${i}" placeholder="Photo ${i} URL" value="${esc(p?.['image_url'+(i===1?'':'_'+i)]||'')}">`).join('')}</div><select class="select" name="active"><option value="true" ${p?.is_active!==false?'selected':''}>Live</option><option value="false" ${p?.is_active===false?'selected':''}>Hidden</option></select><button class="btn gold" type="submit">Save design</button></form>`);$('#productForm').onsubmit=e=>saveProduct(e,id)}
async function saveProduct(e,id){e.preventDefault();let f=new FormData(e.target),old=products.find(x=>x.id===id)||{},urls={};try{for(let i=1;i<=4;i++){let file=f.get('image_file_'+i),current=String(f.get('image_url_'+i)||'').trim();urls[i]=file&&file.size?await uploadImage('product-images',file,'products'):current||old['image_url'+(i===1?'':'_'+i)]||''}}catch(err){return toast(err.message||'Photo upload failed')}let size_prices={};['XS','S','M','L','XL','XXL'].forEach(s=>{let v=String(f.get('size_'+s)||'').trim();if(v!=='')size_prices[s]=Number(v)});let row={name:f.get('name'),price:Number(f.get('price')),category:f.get('category'),description:f.get('description'),production_time:f.get('production_time'),size_prices,image_url:urls[1]||fallbackImg,image_url_2:urls[2]||null,image_url_3:urls[3]||null,image_url_4:urls[4]||null,is_active:f.get('active')==='true',updated_at:new Date().toISOString()};let r=id?await db.from('products').update(row).eq('id',id):await db.from('products').insert(row);if(r.error)return toast(r.error.message);await loadProducts();adminHome();toast('Catalog updated ✨')}
async function deleteProduct(id){if(!confirm('Delete this product?'))return;let r=await db.from('products').delete().eq('id',id);if(r.error)return toast(r.error.message);await loadProducts();adminProducts();toast('Product deleted')}
async function adminOrders(){let {data,error}=await db.from('orders').select('*').order('created_at',{ascending:false});if(error)return toast(error.message);$('#adminContent').innerHTML=`<div class="table-wrap glass"><table class="table"><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th>Update</th></tr>${(data||[]).map(o=>`<tr><td>${o.id.slice(0,8)}<br><span class="muted">${new Date(o.created_at).toLocaleString()}</span></td><td>${esc(o.customer_name)}<br><span class="muted">${esc(o.customer_phone)}</span></td><td>${money(o.total_amount)}</td><td><b>${o.payment_status}</b><br><span class="muted">${o.payment_method}</span></td><td>${o.order_status}</td><td><select class="select" onchange="updateOrder('${o.id}',this.value)"><option value="RECEIVED" ${o.order_status==='RECEIVED'?'selected':''}>RECEIVED</option><option value="PROCESSING" ${o.order_status==='PROCESSING'?'selected':''}>PROCESSING</option><option value="EMBROIDERY" ${o.order_status==='EMBROIDERY'?'selected':''}>EMBROIDERY</option><option value="READY" ${o.order_status==='READY'?'selected':''}>READY</option><option value="SHIPPED" ${o.order_status==='SHIPPED'?'selected':''}>SHIPPED</option><option value="DELIVERED" ${o.order_status==='DELIVERED'?'selected':''}>DELIVERED</option><option value="CANCELLED" ${o.order_status==='CANCELLED'?'selected':''}>CANCELLED</option></select><button class="btn" style="margin-top:6px" onclick="markPaid('${o.id}')">Mark paid</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No orders yet.</td></tr>'}</table></div>`}
async function updateOrder(id,status){if(!isAdmin)return;let r=await db.from('orders').update({order_status:status,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)toast(r.error.message);else{toast('Order status updated');adminOrders()}}
async function markPaid(id){let r=await db.from('orders').update({payment_status:'PAID',updated_at:new Date().toISOString()}).eq('id',id);if(r.error)toast(r.error.message);else adminOrders()}
async function adminLoginActivity(){let {data,error}=await db.from('login_activity').select('*').order('created_at',{ascending:false}).limit(100);if(error)return toast(error.message);$('#adminContent').innerHTML=`<div class="row"><div><div class="eyebrow">Security</div><h3>Login activity</h3></div><button class="btn" onclick="adminHome()">Back</button></div><div class="table-wrap glass"><table class="table"><tr><th>Email</th><th>Type</th><th>Time</th></tr>${(data||[]).map(x=>`<tr><td>${esc(x.email)}</td><td>${x.is_admin?'Admin':'Customer'}</td><td>${new Date(x.created_at).toLocaleString('en-IN')}</td></tr>`).join('')||'<tr><td colspan="3" class="empty">No login activity yet.</td></tr>'}</table></div>`}
async function adminAccounts(){let {data,error}=await db.from('admin_users').select('*').order('created_at',{ascending:true});if(error)return toast(error.message);$('#adminContent').innerHTML=`<div class="row"><div><div class="eyebrow">Access</div><h3>Admin accounts</h3></div><button class="btn" onclick="adminHome()">Back</button></div><form id="adminAddForm" class="form glass"><input class="input" name="email" type="email" placeholder="New admin email" required><button class="btn gold" type="submit">Add admin</button></form><div class="table-wrap glass"><table class="table"><tr><th>Email</th><th>Added</th><th></th></tr>${(data||[]).map(x=>`<tr><td>${esc(x.email)}</td><td>${x.created_at?new Date(x.created_at).toLocaleString('en-IN'):''}</td><td><button class="btn" onclick="removeAdminAccount('${esc(x.email)}')">Remove</button></td></tr>`).join('')}</table></div>`;$('#adminAddForm').onsubmit=addAdminAccount}
async function addAdminAccount(e){e.preventDefault();let email=String(new FormData(e.target).get('email')||'').trim().toLowerCase();if(!email)return;let r=await db.from('admin_users').insert({email});if(r.error)return toast(r.error.message);toast('Admin added');adminAccounts()}
async function removeAdminAccount(email){if(!confirm('Remove admin access for '+email+'?'))return;let r=await db.from('admin_users').delete().eq('email',email);if(r.error)return toast(r.error.message);toast('Admin removed');adminAccounts()}
async function adminCustomOrders(){let {data,error}=await db.from('custom_orders').select('*').order('created_at',{ascending:false});if(error)return toast(error.message);$('#adminContent').innerHTML=`<div class="row"><div><div class="eyebrow">Custom work</div><h3>Custom orders</h3></div><button class="btn" onclick="adminHome()">Back</button></div>${(data||[]).map(c=>`<article class="order-card glass"><div class="row"><b>#${esc(c.id.slice(0,8).toUpperCase())}</b><select class="select" style="max-width:180px" onchange="updateCustomOrder('${c.id}',this.value)"><option value="NEW" ${c.status==='NEW'?'selected':''}>NEW</option><option value="REVIEWING" ${c.status==='REVIEWING'?'selected':''}>REVIEWING</option><option value="ACCEPTED" ${c.status==='ACCEPTED'?'selected':''}>ACCEPTED</option><option value="IN_PROGRESS" ${c.status==='IN_PROGRESS'?'selected':''}>IN PROGRESS</option><option value="COMPLETED" ${c.status==='COMPLETED'?'selected':''}>COMPLETED</option><option value="CANCELLED" ${c.status==='CANCELLED'?'selected':''}>CANCELLED</option></select></div><p>${esc(c.message)}</p><div class="product-gallery">${(c.photo_urls||[]).map(u=>`<img src="${esc(u)}" onclick="window.open('${esc(u)}','_blank')">`).join('')}</div></article>`).join('')||'<div class="empty">No custom orders.</div>'}`}
async function updateCustomOrder(id,status){let r=await db.from('custom_orders').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)return toast(r.error.message);toast('Custom order updated');adminCustomOrders()}